services:
  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  django:
    container_name: django
    build: 
      context: .
      args:
        PROJECT_DIR: ${DJANGO_PROJECT_DIR}
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}    
    volumes:
      - static_volume:${DJANGO_STATICFILES_DIR}
      - media_volume:${DJANGO_MEDIA_DIR}

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - static_volume:${DJANGO_STATICFILES_DIR}
      - media_volume:${DJANGO_MEDIA_DIR}
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    depends_on:
      - django
    environment:
      STATIC_DIR: ${DJANGO_STATICFILES_DIR}
      MEDIA_DIR: ${DJANGO_MEDIA_DIR}
volumes:
  postgres_data:
  static_volume:
  media_volume: