# Generated by Django 4.2.19 on 2025-04-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_productgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товар', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
    ]
