# Generated by Django 4.2.19 on 2025-05-24 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_productimage_is_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='start_from',
            new_name='valid_from',
        ),
        migrations.AddField(
            model_name='price',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), verbose_name='Начало действия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='goods.category'),
        ),
    ]
