# Generated by Django 4.2.19 on 2025-05-27 17:35
import random

from django.db import migrations
from django.core.management import call_command
from django.contrib.auth import get_user_model

from carts.factories import CartItemFactory
from carts.models import Cart
from goods.factories import PriceFactory, ProductFactory, ProductImageFactory
from goods.models import Category
from goods.data import IMAGES


USERNAME = 'test_user'


def create_data(apps, schema_editor):
    User = get_user_model()
    user = User.objects.create_user(
        username=USERNAME ,
        email='test_user@mail.ru',
        password='useruser',
    )
    # Корзина
    cart = Cart.objects.create(user=user)
    # Категории
    call_command('loaddata', 'goods/category.json')
    # Товары, изображения, цены
    for cat in Category.objects.all():
        products = ProductFactory.create_batch(8, category=cat)
        count_product_in_cart = 2
        cat_images = IMAGES[cat.name]
        for product in products:
            PriceFactory.create_batch(4, product=product)
            if count_product_in_cart:
                CartItemFactory(cart=cart, product=product, quantity=1)
                count_product_in_cart -= 1
            index_main_image = random.randint(1,len(cat_images))-1
            for i, img in enumerate(cat_images[random.randint(1,len(cat_images))-1]):
                if i == index_main_image:
                    ProductImageFactory(original=img, product=product, is_main=True)
                    continue
                ProductImageFactory(original=img, product=product)
    

def remove_data(apps, schema_editor):
    """Очищаем таблицы"""
    apps.get_model('goods', 'Product').objects.all().delete()
    apps.get_model('goods', 'Category').objects.all().delete()
    apps.get_model('goods', 'ProductImage').objects.all().delete()
    apps.get_model('goods', 'Price').objects.all().delete()
    apps.get_model('carts', 'Cart').objects.all().delete()
    apps.get_model('carts', 'CartItem').objects.all().delete()
    User = get_user_model()
    User.objects.get(username=USERNAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_productimage_product'),
    ]

    operations = [
        migrations.RunPython(create_data, remove_data),
    ]
