IMAGES = {
    'Столы':[
        (
            "product/original/Artboard_Copy_1.webp",
            "product/original/Artboard_Copy_2.webp",
            "product/original/Artboard_Copy_3.webp",
            "product/original/Artboard_Copy_4.webp",
            "product/original/Artboard_Copy_5.webp",
        ),(
            "product/original/STOEN_1100x1100_1.webp",
            "product/original/STOEN_1100x1100_2.jpg",
            "product/original/STOEN_1100x1100_3.webp",
            "product/original/STOEN_1100x1100_4.webp",
            "product/original/STOEN_1100x1100_5.webp",
            "product/original/STOEN_1100x1100_6.webp",
        )
    ],
    'Стулья':[
        (
            "product/original/kelly_esthetician_stool_1.jpg",
            "product/original/kelly_esthetician_stool_2.jpg",
        ),(
            "product/original/TMB-TUB-1280-BLKBLK_1.webp",
            "product/original/TMB-TUB-1280-BLKBLK_2.webp",
            "product/original/TMB-TUB-1280-BLKBLK_3.webp",
            "product/original/TMB-TUB-1280-BLKBLK_4.webp",
            "product/original/TMB-TUB-1280-BLKBLK_5.webp",
            "product/original/TMB-TUB-1280-BLKBLK_6.jpg",
            "product/original/TMB-TUB-1280-BLKBLK_7.webp",
            "product/original/TMB-TUB-1280-BLKBLK_8.webp",
            "product/original/TMB-TUB-1280-BLKBLK_9.webp",
        )
    ],
    'Системы хранения': [
        (
            "product/original/ETA80N_1100x1100_1.webp",
            "product/original/ETA80N_1100x1100_2.webp",
            "product/original/ETA80N_1100x1100_3.webp",
            "product/original/ETA80N_1100x1100_4.webp",
            "product/original/ETA80N_1100x1100_5.webp",
            "product/original/ETA80N_1100x1100_6.webp",
            "product/original/ETA80N_1100x1100_7.webp",
        ),(
            "product/original/tif_dryer_1.jpeg",
            "product/original/tif_dryer_2.jpeg",
            "product/original/tif_dryer_3.jpg",
            "product/original/tif_pedi2.jpeg",
            "product/original/tif_pedi3.jpeg",
            "product/original/tif_pedi_1.jpeg",
        ),(
            "product/original/POLMEGA_1100x1100_1.webp",
            "product/original/POLMEGA_1100x1100_2.webp",
            "product/original/POLMEGA_1100x1100_3.webp",
            "product/original/POLMEGA_1100x1100_4.webp",
            "product/original/POLMEGA_1100x1100_5.webp",
            "product/original/POLMEGA_1100x1100_6.webp",
        ),
        (
            "product/original/Хранение_1.webp",
            "product/original/Хранение_10.webp",
            "product/original/Хранение_11.webp",
            "product/original/Хранение_2.webp",
            "product/original/Хранение_3.webp",
            "product/original/Хранение_4.webp",
            "product/original/Хранение_5.webp",
            "product/original/Хранение_6.webp",
            "product/original/Хранение_7.webp",
            "product/original/Хранение_8.webp",
            "product/original/Хранение_9.webp",
        )
    ]
}